/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Avatar = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "avatar.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  _type: "image";
};

export type RichTextBlock = {
  _type: "richTextBlock";
  content?: BlockContent;
};

export type CallToAction = {
  _type: "callToAction";
  heading?: string;
  body?: string;
  button?: Link;
};

export type Testimonials = {
  _type: "testimonials";
  heading?: string;
  items?: Array<{
    quote?: string;
    author?: string;
    role?: string;
    avatar?: Avatar;
    _type: "testimonial";
    _key: string;
  }>;
};

export type FeatureGrid = {
  _type: "featureGrid";
  eyebrow?: string;
  heading?: string;
  intro?: string;
  features?: Array<{
    title?: string;
    body?: string;
    icon?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type Hero = {
  _type: "hero";
  eyebrow?: string;
  heading?: string;
  subheading?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ctas?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & FeatureGrid)
  | ({
      _key: string;
    } & Testimonials)
  | ({
      _key: string;
    } & CallToAction)
  | ({
      _key: string;
    } & RichTextBlock)
>;

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type Link = {
  _type: "link";
  label?: string;
  linkType?: "internal" | "external";
  internal?: PageReference | PostReference;
  href?: string;
  openInNewTab?: boolean;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageBuilder?: PageBuilder;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  nav?: Array<
    {
      _key: string;
    } & Link
  >;
  footerNav?: Array<
    {
      _key: string;
    } & Link
  >;
  footerText?: string;
  social?: Array<{
    platform?:
      | "twitter"
      | "instagram"
      | "linkedin"
      | "facebook"
      | "youtube"
      | "github"
      | "tiktok";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  contactEmail?: string;
  contactPhone?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Avatar
  | RichTextBlock
  | CallToAction
  | Testimonials
  | FeatureGrid
  | Hero
  | PageBuilder
  | BlockContent
  | PageReference
  | PostReference
  | Link
  | Seo
  | Category
  | Slug
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  title,  description,  logo,  ogImage,  footerText,  contactEmail,  contactPhone,  nav[]{    _key,    label,    linkType,    openInNewTab,    "href": coalesce(href, "/" + internal->slug.current, "#")  },  footerNav[]{    _key,    label,    linkType,    openInNewTab,    "href": coalesce(href, "/" + internal->slug.current, "#")  },  social[]{ _key, platform, url }}
export type SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  ogImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  footerText: string | null;
  contactEmail: string | null;
  contactPhone: string | null;
  nav: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    openInNewTab: boolean | null;
    href: string | "#";
  }> | null;
  footerNav: Array<{
    _key: string;
    label: string | null;
    linkType: "external" | "internal" | null;
    openInNewTab: boolean | null;
    href: string | "#";
  }> | null;
  social: Array<{
    _key: string;
    platform:
      | "facebook"
      | "github"
      | "instagram"
      | "linkedin"
      | "tiktok"
      | "twitter"
      | "youtube"
      | null;
    url: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(publishedAt desc){    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    mainImage,    "author": author->{ name, "slug": slug.current }  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  author: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  body,  "author": author->{ name, image, bio, "slug": slug.current },  "categories": categories[]->{ _id, title, "slug": slug.current },  seo}
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  body: BlockContent | null;
  author: {
    name: string | null;
    image: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: string | null;
    slug: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  seo: Seo | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POSTS_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{  "slug": slug.current}
export type POSTS_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PAGE_QUERY
// Query: *[_type == "page" && slug.current == $slug][0]{  _id,  title,  "slug": slug.current,  pageBuilder[]{    ...,    _type == "hero" => {      ...,      ctas[]{        _key,        label,        linkType,        openInNewTab,        "href": coalesce(href, "/" + internal->slug.current, "#")      }    },    _type == "callToAction" => {      ...,      button{        label,        linkType,        openInNewTab,        "href": coalesce(href, "/" + internal->slug.current, "#")      }    }  },  seo}
export type PAGE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  pageBuilder: Array<
    | {
        _key: string;
        _type: "callToAction";
        heading?: string;
        body?: string;
        button: {
          label: string | null;
          linkType: "external" | "internal" | null;
          openInNewTab: boolean | null;
          href: string | "#";
        } | null;
      }
    | {
        _key: string;
        _type: "featureGrid";
        eyebrow?: string;
        heading?: string;
        intro?: string;
        features?: Array<{
          title?: string;
          body?: string;
          icon?: string;
          _type: "feature";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "hero";
        eyebrow?: string;
        heading?: string;
        subheading?: string;
        image?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        };
        ctas: Array<{
          _key: string;
          label: string | null;
          linkType: "external" | "internal" | null;
          openInNewTab: boolean | null;
          href: string | "#";
        }> | null;
      }
    | {
        _key: string;
        _type: "richTextBlock";
        content?: BlockContent;
      }
    | {
        _key: string;
        _type: "testimonials";
        heading?: string;
        items?: Array<{
          quote?: string;
          author?: string;
          role?: string;
          avatar?: Avatar;
          _type: "testimonial";
          _key: string;
        }>;
      }
  > | null;
  seo: Seo | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PAGE_SLUGS_QUERY
// Query: *[_type == "page" && defined(slug.current)]{  "slug": slug.current}
export type PAGE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  title,\n  description,\n  logo,\n  ogImage,\n  footerText,\n  contactEmail,\n  contactPhone,\n  nav[]{\n    _key,\n    label,\n    linkType,\n    openInNewTab,\n    "href": coalesce(href, "/" + internal->slug.current, "#")\n  },\n  footerNav[]{\n    _key,\n    label,\n    linkType,\n    openInNewTab,\n    "href": coalesce(href, "/" + internal->slug.current, "#")\n  },\n  social[]{ _key, platform, url }\n}': SETTINGS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]\n  | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    mainImage,\n    "author": author->{ name, "slug": slug.current }\n  }': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  body,\n  "author": author->{ name, image, bio, "slug": slug.current },\n  "categories": categories[]->{ _id, title, "slug": slug.current },\n  seo\n}': POST_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{\n  "slug": slug.current\n}': POSTS_SLUGS_QUERY_RESULT;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id,\n  title,\n  "slug": slug.current,\n  pageBuilder[]{\n    ...,\n    _type == "hero" => {\n      ...,\n      ctas[]{\n        _key,\n        label,\n        linkType,\n        openInNewTab,\n        "href": coalesce(href, "/" + internal->slug.current, "#")\n      }\n    },\n    _type == "callToAction" => {\n      ...,\n      button{\n        label,\n        linkType,\n        openInNewTab,\n        "href": coalesce(href, "/" + internal->slug.current, "#")\n      }\n    }\n  },\n  seo\n}': PAGE_QUERY_RESULT;
    '*[_type == "page" && defined(slug.current)]{\n  "slug": slug.current\n}': PAGE_SLUGS_QUERY_RESULT;
  }
}
