#!/usr/bin/env node
/**
 * Predart Studio — Sanity setup wizard.
 *
 * Connects this clone to a Sanity project by writing .env.local. Run after you
 * have a project id (create/find one at https://www.sanity.io/manage). For a
 * brand-new project you can instead run `pnpm dlx sanity@latest init` which
 * creates the project and can write the env file for you.
 */

const fs = require('node:fs')
const path = require('node:path')
const readline = require('node:readline')

const ROOT = process.cwd()
const ENV_PATH = path.join(ROOT, '.env.local')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

const ask = (question) => new Promise((resolve) => rl.question(question, resolve))

function readExistingEnv() {
  if (!fs.existsSync(ENV_PATH)) return {}
  const out = {}
  for (const line of fs.readFileSync(ENV_PATH, 'utf8').split('\n')) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (match) out[match[1]] = match[2]
  }
  return out
}

function upsertEnv(existing, updates) {
  const merged = { ...existing, ...updates }
  const lines = [
    '# Sanity CMS — generated by `pnpm setup-sanity`. Do not commit (.env.local is gitignored).',
    `NEXT_PUBLIC_SANITY_PROJECT_ID=${merged.NEXT_PUBLIC_SANITY_PROJECT_ID || ''}`,
    `NEXT_PUBLIC_SANITY_DATASET=${merged.NEXT_PUBLIC_SANITY_DATASET || 'production'}`,
  ]
  if (merged.NEXT_PUBLIC_SANITY_API_VERSION) {
    lines.push(`NEXT_PUBLIC_SANITY_API_VERSION=${merged.NEXT_PUBLIC_SANITY_API_VERSION}`)
  }
  lines.push(`SANITY_API_READ_TOKEN=${merged.SANITY_API_READ_TOKEN || ''}`)
  // Preserve any unrelated keys already present.
  for (const [key, value] of Object.entries(existing)) {
    if (!lines.some((l) => l.startsWith(`${key}=`)) && !key.startsWith('NEXT_PUBLIC_SANITY') && key !== 'SANITY_API_READ_TOKEN') {
      lines.push(`${key}=${value}`)
    }
  }
  return lines.join('\n') + '\n'
}

async function main() {
  console.log('\nPredart Studio — Sanity setup\n')
  console.log('Find these at https://www.sanity.io/manage → project → API.\n')

  const existing = readExistingEnv()

  const projectId = (
    await ask(`Project ID${existing.NEXT_PUBLIC_SANITY_PROJECT_ID ? ` [${existing.NEXT_PUBLIC_SANITY_PROJECT_ID}]` : ''}: `)
  ).trim()
  if (!projectId && !existing.NEXT_PUBLIC_SANITY_PROJECT_ID) {
    console.error('\n✗ A project ID is required. Aborting.')
    rl.close()
    process.exit(1)
  }
  if (projectId && !/^[a-z0-9-]+$/.test(projectId)) {
    console.error('\n✗ Project ID may only contain a-z, 0-9 and hyphens. Aborting.')
    rl.close()
    process.exit(1)
  }

  const dataset =
    (await ask(`Dataset [${existing.NEXT_PUBLIC_SANITY_DATASET || 'production'}]: `)).trim() ||
    existing.NEXT_PUBLIC_SANITY_DATASET ||
    'production'

  const token = (
    await ask('Read token (optional, enables Draft Mode — press Enter to skip): ')
  ).trim()

  const contents = upsertEnv(existing, {
    NEXT_PUBLIC_SANITY_PROJECT_ID: projectId || existing.NEXT_PUBLIC_SANITY_PROJECT_ID,
    NEXT_PUBLIC_SANITY_DATASET: dataset,
    SANITY_API_READ_TOKEN: token || existing.SANITY_API_READ_TOKEN,
  })

  fs.writeFileSync(ENV_PATH, contents)
  console.log(`\n✓ Wrote ${path.relative(ROOT, ENV_PATH)}`)

  console.log('\nNext steps:')
  console.log('  1. Allow this origin to talk to your project (CORS):')
  console.log('       pnpm dlx sanity@latest cors add http://localhost:3000 --credentials')
  console.log('  2. Generate types from your schema:')
  console.log('       pnpm typegen')
  console.log('  3. Deploy the schema so the Studio + content tools see it:')
  console.log('       pnpm dlx sanity@latest schema deploy')
  console.log('  4. Start the app and open the Studio:')
  console.log('       pnpm dev   →   http://localhost:3000/studio\n')

  rl.close()
}

main().catch((error) => {
  console.error(error)
  rl.close()
  process.exit(1)
})
