// Shared animation infra (predart-starter).
// Import the GSAP motion wrappers from here.
//
// All GSAP-based, scroll/pointer-driven, and respect prefers-reduced-motion
// (render the final, static state instantly):
//   - TextScramble     (ScrambleText)
//   - Magnetic         (pointer-follow)
//   - DrawPath         (DrawSVG draw-on-scroll)
//   - VelocitySkew     (scroll-velocity skew)
//   - ImageFollowList  (cursor-follow thumbnail list)
//
// Pure, framework-free math for these lives in `lib/motion/*` (unit-tested).
// NEVER bind Framer Motion to the same property a GSAP wrapper drives.

export { LenisProvider } from './lenis-provider'
export { TextScramble } from './text-scramble'
export { Magnetic } from './magnetic'
export { DrawPath } from './draw-path'
export { VelocitySkew } from './velocity-skew'
export { ImageFollowList, type FollowItem } from './image-follow-list'
// Ported from annnimate.com (clean-room, GSAP-only) — see MOTION-PORT-REPORT.md
export { Typewriter } from './typewriter'
export { CharacterAppear } from './character-appear'
export { TextReveal } from './text-reveal'
export { DualScramble } from './dual-scramble'
export { TextSplitZoom } from './text-split-zoom'
export { VelocityClip } from './velocity-clip'
export { Counter } from './counter'
export { Marquee } from './marquee'
export { Parallax } from './parallax'
export { RectangleTextReveal } from './rectangle-text-reveal'
export { PoppingText } from './popping-text'
export { MaskReveal } from './mask-reveal'
export { FoldingText } from './folding-text'
export { ElementReveal } from './element-reveal'
export { CinematicText } from './cinematic-text'
export { MultiFlip, type MultiFlipItem } from './multi-flip'
export { ScrollProgress } from './progress'
export { HideHeader } from './hide-header'
export { FlipZone } from './flip-zone'
export { RandomRotate } from './random-rotate'
export { AnimatedGrid } from './animated-grid'
export { TextShimmerWave } from './text-shimmer-wave'
export { TextUnderline } from './text-underline'
export { BackgroundColor } from './background-color'
export { InfiniteParallaxSlider } from './infinite-parallax-slider'
export { ImageTrail } from './image-trail'
export { CircularSlider, type CircularSliderItem } from './circular-slider'
export { MotionTooltip } from './tooltip'
export { MorphingDialog } from './morphing-dialog'
export { MotionAccordion, type MotionAccordionItem } from './accordion'
export { HoverableList, type HoverableListItem } from './hoverable-list'
export { Card3DFlip } from './card-3d-flip'
export { CustomCursor } from './custom-cursor'
export { RainbowButton } from './rainbow-button'
export { IconButton } from './icon-button'
export { CurveFillButton } from './curve-fill-button'
export { CircleFillButton } from './circle-fill-button'
export { BackgroundFillButton } from './background-fill-button'
export { InfiniteDraggableGrid } from './infinite-draggable-grid'
export { GooeyMenu } from './gooey-menu'
export { MegaMenu } from './mega-menu'
export { MultiLevelDrawerMenu } from './multi-level-drawer-menu'
export { FullscreenSlideMenu } from './fullscreen-slide-menu'
export { TextMorph } from './text-morph'
export { GooeyHoverReveal } from './gooey-hover-reveal'
export { MeshGradient } from './mesh-gradient'
export { ImageDissolveScroll } from './image-dissolve-scroll'
// Ported from pixel-point/animate-text (clean-room, GSAP-only) — see MOTION-PORT-REPORT.md
export { SoftBlur } from './soft-blur'
// animate-text catalog — entrance reveals (one-shot, scroll-triggered)
export { PerCharacterRise } from './per-character-rise'
export { PerWordCrossfade } from './per-word-crossfade'
export { SpringScaleIn } from './spring-scale-in'
export { MaskRevealUp } from './mask-reveal-up'
export { LineByLineSlide } from './line-by-line-slide'
export { TypewriterSteps } from './typewriter-steps'
export { MicroScaleFade } from './micro-scale-fade'
export { ShimmerSweep } from './shimmer-sweep'
export { BottomUpLetters } from './bottom-up-letters'
export { TopDownLetters } from './top-down-letters'
export { DepthParallaxWords } from './depth-parallax-words'
export { StaggerFromCenter } from './stagger-from-center'
export { StaggerFromEdges } from './stagger-from-edges'
export { ShortSlideRight } from './short-slide-right'
export { KineticCenterBuild } from './kinetic-center-build'
export { ShortSlideDown } from './short-slide-down'
// animate-text catalog — swap transitions (auto-cycling between phrases)
export { FadeThrough } from './fade-through'
export { SharedAxisX } from './shared-axis-x'
export { SharedAxisY } from './shared-axis-y'
export { SharedAxisZ } from './shared-axis-z'
export { BlurOutUp } from './blur-out-up'
export { ScaleDownFade } from './scale-down-fade'
export { FocusBlurResolve } from './focus-blur-resolve'
